### ISSUE TITLE
Add top-level `plots` section

### ISSUE THREAD

**Issue by daavoo** [iterative/dvcyaml-schema#14]
Per https://github.com/iterative/dvc/pull/7477

**Comment by dberenbaum** [comment]
This may be important for https://github.com/iterative/vscode-dvc/issues/1192.

**Comment by skshetry** [comment]
We should keep the implementation and this schema always in sync.

What's the format of `plots`? In the schema, I only see `dict` (cc @pared, the schema should be stricter): https://github.com/iterative/dvc/blob/512bfc4305a7607f63514dc734663c973ed954b2/dvc/schema.py#L59.

Let me know if you need help here. :)

**Comment by pared** [comment]
Sorry, @skshetry I didn't add it to my TODO's, I don't expect that help will be needed, adding it rn.
