### ISSUE TITLE
Rename repo to dvc-yaml-schema ?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvcyaml-schema#4]
It's `pipeline-schema` now. The README has title `dvc-pipeline-schema` though. But really it's the JSON schema for `dvc.yaml` files.

The only problem is that it's not clear why a YAML file has a JSON schema 😅

**Comment by jorgeorpinel** [comment]
p.s. does it also work for `dvc.lock` files?

**Comment by skshetry** [comment]
@jorgeorpinel, _dvc-yaml-schema_ or _dvcyaml-schema_?

**Comment by jorgeorpinel** [comment]
Hmmm I vote for `dvcyaml-schema` but don't have a strong opinion.

BTW, does this schema also cover dvc.lock files? Thanks

**Comment by skshetry** [comment]
dvcyaml-schema is one character short. Going with that.

**Comment by skshetry** [comment]
Fixed by  cedc48b.

**Comment by jorgeorpinel** [comment]
Thanks
